### ISSUE TITLE
"Error: Verifying blocks" should be retried

### ISSUE THREAD

**Issue by schildbach** [hsjoberg/fork-explorer#45]
When starting up bitcoind and fork-explorer at the same time, I've seen this error from bitcoind and fork-explorer exits:

```
fork-explorer_1     | Bootstrapping real block data...
fork-explorer_1     | Listening on: http://0.0.0.0:8080
fork-explorer_1     | error: Uncaught (in promise) Error: Verifying blocks...
fork-explorer_1     |     throw new Error(response.error.message);
fork-explorer_1     |           ^
fork-explorer_1     |     at getblockcount (file:///fork-explorer/backend/jsonrpc/index.ts:11:11)
fork-explorer_1     |     at async bootstrapBlocks (file:///fork-explorer/backend/blocks/index.ts:87:20)
```

This is only a temporary error, so I propose it should be retried until it's gone.

**Comment by hsjoberg** [comment]
Yes, makes sense to retry. At least a couple of times.
