### ISSUE TITLE
Issue running on development env

### ISSUE THREAD

**Issue by skmcontrib** [hsjoberg/fork-explorer#81]
When I am running ./build-frontend.sh getting this error on windows. Have followed the README.md and using deno 1.9.2
on deno 1.10.x gives a different error shown here https://github.com/alephjs/aleph.js/issues/312
any suggestions @hsjoberg ?

INFO Download https://deno.land/x/aleph@v0.3.0-alpha.32/framework/react/pagedata.ts
INFO Download https://deno.land/x/aleph@v0.3.0-alpha.32/framework/react/pageprops.ts
ERROR Load module '/back/config/config.ts': No such file
ERROR Load module '/back/common/data.ts': No such file
ERROR Load module '/back/common/interfaces.ts': No such file
ERROR Write module '/pages/about.tsx' to JS: No such file
ERROR Write module '/pages/index.tsx' to JS: No such file
ERROR Write module '/pages/miners.tsx' to JS: No such file
ERROR Write module '/pages/stats.tsx' to JS: No such file
ERROR Write module '/pages/settings.tsx' to JS: No such file
ERROR Write module '/pages/miner/[name].tsx' to JS: No such file
error: Uncaught (in promise) Error: No such file
        return Promise.reject(new Error(`No such file`))
                              ^
    at Application.fetchModule (https://deno.land/x/aleph@v0.3.0-alpha.32/server/app.ts:892:31)
    at Application.loadModule (https://deno.land/x/aleph@v0.3.0-alpha.32/server/app.ts:968:33)
    at Application.compile (https://deno.land/x/aleph@v0.3.0-alpha.32/server/app.ts:1102:37)
    at https://deno.land/x/aleph@v0.3.0-alpha.32/server/app.ts:1187:47
    at Array.map (<anonymous>)
    at Application.compile (https://deno.land/x/aleph@v0.3.0-alpha.32/server/app.ts:1186:74)
    at async Promise.all (index 1)
    at async Application.init (https://deno.land/x/aleph@v0.3.0-alpha.32/server/app.ts:284:5)
    at async Application.build (https://deno.land/x/aleph@v0.3.0-alpha.32/server/app.ts:792:5)
    at async default (https://deno.land/x/aleph@v0.3.0-alpha.32/cli/build.ts:18:3)

**Comment by hsjoberg** [comment]
@skmcontrib Hmm, sorry I am not sure. I haven't tried building on Windows actually.
The issue appears to be related the `back` symlink required for the frontend project to reach the folder above itself, but this doesn't appear to work correctly under Windows.

Are you familiar with WSL in Windows? If so, could you trying running it there?
